var data = [
    {
        code: 'PLAT_ORG_COMPANY',
        display: 1,
        id: '10026',
        name: '单位管理',
        pid: '10025',
        showIcon: null,
        sortValue: 99,
        url: '/platform/organization/company',
    },
    {
        code: 'PLAT_ORG_COMPANY',
        display: 1,
        id: '10026',
        name: '单位管理',
        pid: '10025',
        showIcon: null,
        sortValue: 99,
        url: '/platform/organization/company',
    },
    {
        code: 'PLAT_ORG_COMPANY',
        display: 1,
        id: '10026',
        name: '单位管理',
        pid: '10025',
        showIcon: null,
        sortValue: 99,
        url: '/platform/organization/company',
    },
    {
        code: 'PLAT_ORG_COMPANY',
        display: 1,
        id: '10026',
        name: '单位管理',
        pid: '10025',
        showIcon: null,
        sortValue: 99,
        url: '/platform/organization/company',
    },
    {
        code: 'PLAT_ORG_COMPANY',
        display: 1,
        id: '10026',
        name: '单位管理',
        pid: '10025',
        showIcon: null,
        sortValue: 99,
        url: '/platform/organization/company',
    },
]